#!/bin/bash

# Script: Ops301Challenge02
# Purpose: Date and Time

# How to show time and date
year=`date +%Y`
echo $year
month=`date +%m`
day=`date +%d`

# Time displayed in UTC.
# UTC is the primary time standard.
# UTC is the basis for modern timekeeping.
hour=`date +%H`
minute=`date +%M`
second=`date +%S`

# Put it together
echo "Current Date: $day-$month-$year"
echo "Current Date: $hour:$minute:$second"

# How to row append

# First create a file testfile.txt and add some lines to it.
echo "Original file before append:"
cat testfile.txt

# The >> double carrot will row append
echo "Jose coppied this with date: `date`" >> testfile.txt
echo "Appended file: "
cat testfile.txt

# End
